app:
  llm:
    model: gemma-3-12b-it-qat
    url: http://localhost:1234/v1
    need-auth: false
    api-key:
  modules:
    cmd-worker:
      enabled: true
    databaseworker:
      enabled: false
      datasource:
        jdbc-url: jdbc:postgresql://XXX
        username: XXX
        password: XXX
        driver-class-name: org.postgresql.Driver
    gui:
      enabled: true
  version: 0.1.0

spring:
  config:
    import: file:./additional.yml
  application:
    name: SmartModuleSystemAi
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB

  #  main:
  #    web-application-type: reactive

server:
  port: 8089
  ssl:
    enabled: false
    key-store: keystore.p12
    key-store-password: xxx
    key-store-type: PKCS12
    key-alias: tomcat

logging:
  file:
    name: smsai.log
  level:
    root: info